# Base configuration
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
highlighter: rouge

collections:
  pages:
    output: true
    permalink: /:path/

# Title
name: GA Cloud Governance
subtitle: GA Cloud Governance template

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
baseurl: ''

# Author/Organization info to be displayed in the templates
author:
  name: Geoscience Australia
  url: http://intranet.ga.gov.au/

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: 'http://www.ga.gov.au/__data/assets/image/0013/16510/ga-logo.jpg'
logoalt:

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: ./
  internal: true
- text: Governance
  url: example_page/
  internal: true
- text: Geoscience Australia Intranet
  url: http://intranet.ga.gov.au/
  internal: false

# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: GA cloud Governance Repo
  description: Source file.
  url: https://github.com/d3lerium/d3lerium.github.io/

# Style Variables
brand_color: "#2cb34a"

